#!/usr/bin/env python3
"""
Generate the preview pages.

The chrome (unofficial ribbon, brand bar, the Y's nav, the sub-nav across these
previews, footer) is identical on every page, so it lives here. Run `python3 build.py`
and commit the HTML it writes; GitHub Pages serves plain static files.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Published Pool Relay views. Each is scoped to exactly what its page is about.
EMBED = {
    "finder":  "zhzk448Thgeod0PjWntw82",   # every Y, every program, one day; Program menu
    "lap":     "oIqQALO9J4LAqlhYZCvYpv",   # lap swim at every Y, one day
    "lessons": "CjkIGvPPrv5ZqlNdFNzG8C",   # group lessons at every Y, one day; level menu
    "team":    "T2pTbHBy00qUJanIgYhGmi",   # the two swim team schedules that are published
    "fit":     "MQnVkkXruVn39uYNJiyHYE",   # water fitness at every Y, one day
    "open":    "tFHqGU9MMALSmd1fjzDvcm",   # rec swim, splash pads, feature pools
    "one":     "e3kuZyCtwPu86rA2JFVHqa",   # one Y, the whole week; Facilities menu
}

NAV = [
    ("index.html",         "Find a swim time"),
    ("lap-swim.html",      "Lap Swim"),
    ("swim-lessons.html",  "Swim Lessons"),
    ("swim-team.html",     "Swim Teams"),
    ("water-fitness.html", "Water Fitness"),
    ("open-swim.html",     "Open & Family Swim"),
    ("locations.html",     "One Y, the whole week"),
]

SITE = "https://ymcacf.org"


def cal(key, title, cls="", caption=""):
    """One live calendar plus its caption line."""
    token = EMBED[key]
    tail = f" &nbsp;&mdash;&nbsp; {caption}" if caption else ""
    return f"""  <div class="cal {cls}">
    <iframe width="100%" height="640" src="https://www.poolrelay.com/embed/{token}"
            title="{title}" loading="lazy"></iframe>
  </div>
  <p class="capt">Live from Pool Relay &middot;
    <a href="https://www.poolrelay.com/v/{token}" target="_blank" rel="noopener">open the full calendar &rarr;</a>{tail}
  </p>
"""


def shell(slug, title, description, body):
    subnav = "\n".join(
        '    <li{on}><a href="{href}">{label}</a></li>'.format(
            on=' class="on"' if href == slug else "", href=href, label=label)
        for href, label in NAV)
    return f"""<!DOCTYPE html>
<!--
  UNOFFICIAL PREVIEW. Not a YMCA of Central Florida website.
  Generated by build.py — edit that, not this file.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="style.css">
</head>
<body>

<div class="ribbon">
  <b>Unofficial preview.</b> Not a YMCA of Central Florida page. A mockup of an aquatics section for
  <a href="{SITE}/" target="_blank" rel="noopener">ymcacf.org</a> with live
  <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool&nbsp;Relay</a> calendars.
</div>

<header class="brandbar">
  <div class="wrap inner">
    <a class="mark" href="index.html"><span class="city">YMCA OF CENTRAL FLORIDA</span>Aquatics</a>
    <div class="tel">14 pools &middot; one schedule</div>
  </div>
</header>

<nav class="main">
  <ul>
    <li><a href="{SITE}/membership/" target="_blank" rel="noopener">Memberships</a></li>
    <li class="on"><a href="index.html">Swimming</a></li>
    <li><a href="{SITE}/programs/" target="_blank" rel="noopener">Programs &amp; Classes</a></li>
    <li><a href="{SITE}/locations/" target="_blank" rel="noopener">Locations</a></li>
    <li><a href="{SITE}/schedules/" target="_blank" rel="noopener">Schedules</a></li>
  </ul>
</nav>

<nav class="sub">
  <ul>
{subnav}
  </ul>
</nav>

{body}
<footer>
  <div class="wrap">
    <p><strong>Unofficial preview.</strong> Built to show what one aquatics schedule for all fourteen
    YMCA of Central Florida pools could look like. Not affiliated with the YMCA of Central Florida.</p>
    <p>Read on 24 September 2026 from the Y's fourteen location pages (pool hours), each location's
    class schedule, the <a href="{SITE}/programs/swim/swim-lessons/" target="_blank" rel="noopener">swim
    lesson program finder</a> (every group lesson session with open spots), and the
    <a href="{SITE}/programs/swim/sports/" target="_blank" rel="noopener">swim team pages</a>. Calendars by
    <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool Relay</a>.</p>
  </div>
</footer>

</body>
</html>
"""


# ── The findings block, on the hub ─────────────────────────────────────────────
QUESTIONS = """<section class="wrap">
  <h2>Questions for the aquatics team</h2>
  <p>Everything on these calendars comes from what the Y publishes. These are the places where two
  of its own sources disagree, where a schedule isn't published, or where we had to make a call.</p>

  <ul class="qa">
    <li>
      <div class="q"><span class="tag ours">Ours</span>Pool hours shown as lap swim</div>
      <div class="a">Twelve location pages give pool hours, not lap swim times, and none say which lanes
      are held for laps while lessons and classes run. We show the pool hours as lap swim in a
      &ldquo;Lap Lanes&rdquo; part of each pool, and lessons and classes in a &ldquo;Program Area&rdquo;
      beside it. Roper and Winter Park publish lap swim itself, and those times are used as given.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Swim team practice times</div>
      <div class="a">The Developmental team lists 11 locations and the USA Swim team 5, and both pages
      say to fill out an interest form &ldquo;to see specific days and times for each location.&rdquo;
      Only Winter Park and Dr. P. Phillips put practices on their class schedules, so only those two are
      on the swim team calendar.</div>
    </li>
    <li>
      <div class="q"><span class="tag clash">Conflict</span>Winter Park: lap swim and swim team, 4&ndash;7pm</div>
      <div class="a">Winter Park's schedule has open lap swim until 7pm Monday through Thursday and swim
      team practice 4&ndash;7pm Tuesday through Thursday, both in the Lap Pool. How many lanes stay open
      for lap swimmers? Say, and the calendar shows it lane by lane.</div>
    </li>
    <li>
      <div class="q"><span class="tag clash">Conflict</span>Dr. P. Phillips Developmental practice at 7:30am?</div>
      <div class="a">The class schedule lists Developmental Swim Team Monday, Tuesday and Thursday
      7:30&ndash;8:30am, through December 1. A school-day morning practice is unusual; is it 7:30pm?</div>
    </li>
    <li>
      <div class="q"><span class="tag clash">Conflict</span>Roper: two sets of lap swim hours</div>
      <div class="a">The Roper location page gives pool hours Monday&ndash;Thursday 7&ndash;12:30 and
      4&ndash;7:30. Its class schedule lists lap swim Monday, Wednesday and Friday mornings and
      5&ndash;7:30pm Monday&ndash;Thursday. We used the class schedule; are Tuesday and Thursday
      mornings open?</div>
    </li>
    <li>
      <div class="q"><span class="tag clash">Conflict</span>Lessons after the pool closes</div>
      <div class="a">Leonard &amp; Marjorie Williams lists its pool open until 7pm, and Tuesday
      Teen/Adult lessons at 7:00&ndash;7:30pm.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Session dates that don't add up</div>
      <div class="a">At Osceola, Sunday School Age Stage 5 is a 4-lesson session listed as ending
      Wednesday, November 18, and Sunday Teen/Adult ends November 1, which is three Sundays. We showed
      both as four Sundays from October 18.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Smaller things</div>
      <div class="a">Osceola's Friday lap swim reads &ldquo;3:00 am &ndash; 5:45pm&rdquo; (shown as
      3pm). Frank DeLuca's Thursday and Friday Water Fitness are listed in Studio A (shown in the pool).
      Osceola and Wayne Densch have no classes on their class schedules at all.</div>
    </li>
  </ul>
</section>

"""


# ══ 1. The hub: find a swim time ══════════════════════════════════════════════
HUB = f"""<section class="wrap hero">
  <div class="crumb">Programs &amp; Classes &raquo; Swimming</div>
  <h1>Find a swim time at any Y</h1>
  <p class="kicker">14 pools &middot; lap swim, lessons, teams, water fitness, open swim</p>
  <p class="lead">Every YMCA of Central Florida pool on one calendar, one row per pool. Pick a
  <strong>day</strong>, then use the <strong>Teams</strong> menu to show one program, or leave it on
  <strong>All</strong>. Tap any block for details.</p>

{cal("finder", "YMCA of Central Florida — every pool, one day", "tall",
     caption="Fall lesson sessions start Saturday, October 17: tap the date and pick it.")}

  <div class="try">
    <div><b>Laps at 6am on a Tuesday?</b>Seven Ys: Downtown, Dr. P. Phillips, Frank DeLuca, Golden
    Triangle, J. Douglas Williams, Oviedo and Winter Park.</div>
    <div><b>Preschool lessons on a Saturday morning?</b>Ten Ys, from 8:15am at Golden Triangle to noon
    at Lake Nona. Each block shows the spots still open.</div>
    <div><b>Adult lessons after work?</b>Downtown at 6pm Tuesday and Thursday; Oviedo and Leonard
    &amp; Marjorie Williams at 7pm.</div>
  </div>
</section>

<div class="trail">
  <div class="wrap">
    <h2>One question, fourteen websites</h2>
    <p class="q">&ldquo;Where can I swim laps before work on Tuesday?&rdquo;</p>
    <p>Today, answering that on ymcacf.org means:</p>
    <ol>
      <li>Open the Locations page and pick a Y.</li>
      <li>Find pool hours in that Y's hours list. They are pool hours, not lap swim hours.</li>
      <li>Open that Y's Family Center Schedule. It covers group exercise, not lap swim, and the
      schedule loads only when you scroll to it.</li>
      <li>Go back and do it again, up to thirteen more times.</li>
    </ol>
    <p>Swim lessons are in a separate finder that searches one program at a time. Swim team practice
    times aren't published at all: both team pages ask families to fill out an interest form to see them.</p>
    <p class="answer">On this calendar it's one look: pick Tuesday, choose <b>Lap Swim</b>, and every
    Y that's open at 6am is on the screen, <b>with its lessons, classes and team practices beside
    it</b>. The Y's own staff keep it current in an AI chat, and every page on the site updates at once.</p>
  </div>
</div>

<section class="wrap">
  <h2>By program</h2>
  <div class="cards">
    <a class="card" href="lap-swim.html"><div class="pic lap"></div><div class="body">
      <h3>Lap Swim</h3><p>Every Y's lap swim, one row per pool, one day at a time.</p></div></a>
    <a class="card" href="swim-lessons.html"><div class="pic les"></div><div class="body">
      <h3>Swim Lessons</h3><p>424 fall sessions at 11 Ys, by level, with open spots.</p></div></a>
    <a class="card" href="swim-team.html"><div class="pic team"></div><div class="body">
      <h3>Swim Teams</h3><p>Developmental and USA Swimming practice times.</p></div></a>
    <a class="card" href="water-fitness.html"><div class="pic fit"></div><div class="body">
      <h3>Water Fitness</h3><p>Aqua Zumba, deep and shallow water classes at 12 Ys.</p></div></a>
    <a class="card" href="open-swim.html"><div class="pic open"></div><div class="body">
      <h3>Open &amp; Family Swim</h3><p>Recreational swim, splash pads and feature pools.</p></div></a>
    <a class="card" href="locations.html"><div class="pic loc"></div><div class="body">
      <h3>One Y, the whole week</h3><p>Everything in one Y's pools, Sunday to Saturday.</p></div></a>
  </div>
</section>

{QUESTIONS}"""


# ══ 2. Lap Swim ═══════════════════════════════════════════════════════════════
LAP = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Swimming</a> &raquo; Lap Swim</div>
  <h1>Lap Swim</h1>
  <p class="kicker">14 Ys &middot; from 5am Downtown to 9:30pm</p>
  <p class="lead">Lap swim at every YMCA of Central Florida pool, included with membership. Pick a
  day; each row is one pool.</p>

{cal("lap", "YMCA of Central Florida — lap swim at every Y", "tall",
     caption="Tap a block to see the pool and the source of its hours.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>Pool hours are not lap swim hours</h2>
    <p>Every location page lists when its pool is open. A swimmer who shows up at
    9:30 on a weekday at Oviedo finds Shallow Water Fitness in the water; at Winter Park after 4pm on a
    Tuesday, swim team practice shares the lap pool.</p>
    <p class="answer">On the calendar, lap swim stops where the Y's own schedule says something else
    is in the water. With the <b>number of lanes</b> each program takes, it would say how many lanes
    are left too, the way it already does for pools like
    <a href="https://psmoore.github.io/pool_penbay/" target="_blank" rel="noopener" style="color:#ffc08f">Penobscot Bay YMCA</a>.</p>
  </div>
</div>

"""


# ══ 3. Swim Lessons ═══════════════════════════════════════════════════════════
LESSONS = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Swimming</a> &raquo; Swim Lessons</div>
  <h1>Group Swim Lessons</h1>
  <p class="kicker">Fall sessions from October 17 &middot; 11 Ys &middot; ages 6 months to adult</p>
  <p class="lead">Four-week group lesson sessions, $55 for members and $95 for non-members. Pick a
  day, and use the <strong>Practice Groups</strong> menu to show one level: Swim Starters (6 months to
  3 years), Preschool (3&ndash;5), School Age (6&ndash;12) or Teen &amp; Adult.</p>

  <div class="note"><span class="hd">Sessions start October 17</span>
  The calendar opens on today, before the fall sessions begin. Tap the date at the top, then
  <b>&rsaquo;</b> to October and pick Saturday the 17th.</div>

{cal("lessons", "YMCA of Central Florida — swim lessons at every Y", "tall",
     caption="Each block lists the levels at that time and the spots still open in each.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>&ldquo;What's open for my four-year-old on Saturday?&rdquo;</h2>
    <p>The Y's lesson finder can answer this, but for one lesson type at a time, starting from a zip
    code, as a list of cards. Comparing Preschool at three nearby Ys means three searches and a notepad.</p>
    <p class="answer">Here, choose <b>Preschool</b> and <b>Saturday, October 17</b>: every Y
    offering it is on one screen, in time order, <b>with the open spots in each class</b>. It's the same
    data the finder uses, 424 sessions, laid out as a schedule.</p>
  </div>
</div>

"""


# ══ 4. Swim Teams ═════════════════════════════════════════════════════════════
TEAM = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Swimming</a> &raquo; Swim Teams</div>
  <h1>Swim Teams</h1>
  <p class="kicker">Developmental at 11 Ys &middot; USA Swimming at 5</p>
  <p class="lead">The Developmental Swim Team is the step after swim lessons, with optional meets.
  The USA Swim Team practices five days a week and competes. Ages 6&ndash;17.</p>

{cal("team", "YMCA of Central Florida — swim team practice", "short",
     caption="Only Winter Park and Dr. P. Phillips publish practice times today.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>The schedule behind the interest form</h2>
    <p>Both swim team pages list their locations, then say: <i>&ldquo;Fill out the interest form below
    to see specific days and times for each location.&rdquo;</i> Winter Park and Dr. P. Phillips put their
    practices on their class schedules, so those two are here. For the other locations, a family has
    to give their contact details and wait to find out when practice is.</p>
    <p class="answer">With each team's groups and times entered once, this calendar shows
    <b>every location's practices side by side</b>. Parents compare before they call, coaches see the
    lanes they hold, and lap swimmers see which lanes are left.</p>
  </div>
</div>

<section class="wrap">
  <h2>Where the teams practice</h2>
  <div class="scroller">
  <table class="sched">
    <thead><tr><th>Location</th><th>Developmental</th><th>USA Swimming</th></tr></thead>
    <tbody>
      <tr><td>Downtown Orlando</td><td class="n">&#10003;</td><td class="n">&#10003;</td></tr>
      <tr><td>Dr. P. Phillips</td><td class="n">&#10003; on the calendar</td><td class="n">&#10003;</td></tr>
      <tr><td>Frank DeLuca</td><td class="n">&#10003;</td><td></td></tr>
      <tr><td>Golden Triangle</td><td class="n">&#10003;</td><td></td></tr>
      <tr><td>J. Douglas Williams</td><td class="n">&#10003;</td><td class="n">&#10003;</td></tr>
      <tr><td>Lake Nona</td><td class="n">&#10003;</td><td class="n">&#10003;</td></tr>
      <tr><td>Leonard &amp; Marjorie Williams</td><td class="n">&#10003;</td><td></td></tr>
      <tr><td>Osceola</td><td class="n">&#10003;</td><td class="n">&#10003;</td></tr>
      <tr><td>Oviedo</td><td class="n">&#10003;</td><td></td></tr>
      <tr><td>Titusville (until November)</td><td class="n">&#10003;</td><td></td></tr>
      <tr><td>Winter Park</td><td class="n">&#10003; on the calendar</td><td></td></tr>
    </tbody>
  </table>
  </div>
  <p class="capt">Developmental: $85 a month for Plus and Max members, $200 for non-members. USA Swimming:
  $150 a month for Plus and Max members, $300 for non-members, plus a $40 annual registration.</p>
</section>

"""


# ══ 5. Water Fitness ══════════════════════════════════════════════════════════
FIT = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Swimming</a> &raquo; Water Fitness</div>
  <h1>Water Fitness</h1>
  <p class="kicker">12 Ys &middot; weekday mornings &middot; included with membership</p>
  <p class="lead">Aqua Zumba, shallow and deep water fitness, water tai chi and more, from every Y's
  class schedule on one calendar. Pick a day.</p>

{cal("fit", "YMCA of Central Florida — water fitness at every Y", "tall",
     caption="Almost every class is between 9 and noon on a weekday.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>Fourteen class schedules, one pool of classes</h2>
    <p>Each Y's water fitness is in its own class schedule, among the cycling, BODYPUMP and racquetball
    court bookings, in a strip of a few rows you scroll inside the page.</p>
    <p class="answer">Here are only the classes in the water, <b>every Y at once</b>. A member between
    Oviedo and Winter Park can see that Oviedo has Shallow Water Fitness at 9:15 every weekday and
    Winter Park has Aqua Deep at 9:45.</p>
  </div>
</div>

"""


# ══ 6. Open & Family Swim ═════════════════════════════════════════════════════
OPEN = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Swimming</a> &raquo; Open &amp; Family Swim</div>
  <h1>Open &amp; Family Swim</h1>
  <p class="kicker">Recreational swim &middot; splash pads &middot; feature pools</p>
  <p class="lead">Recreational swim in the Downtown indoor pool, the splash pads at Leonard &amp;
  Marjorie Williams and Osceola, the Dr. P. Phillips feature pool (open through November 22), and the
  Winter Park splash park on weekends.</p>

{cal("open", "YMCA of Central Florida — open and family swim",
     caption="Seasonal pools end on their last day, so nobody has to remember to take them down.")}
</section>

"""


# ══ 7. One Y, the whole week ══════════════════════════════════════════════════
ONE = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Swimming</a> &raquo; One Y, the whole week</div>
  <h1>Your Y's pool, all week</h1>
  <p class="kicker">Pick your Y from the Facilities menu</p>
  <p class="lead">Everything in one Y's pools, Sunday to Saturday: lap swim, lessons, classes and team
  practice together. This is the calendar each location page could embed in place of its
  pool-hours list.</p>

{cal("one", "YMCA of Central Florida — one Y, the whole week", "tall",
     caption="Opens on Winter Park; the <strong>Facilities</strong> menu switches to any of the 14.")}
</section>

<section class="wrap">
  <h2>The pools</h2>
  <div class="facts">
    <div><b>Downtown Orlando</b>Indoor and outdoor pools. 433 N Mills Ave.</div>
    <div><b>Dr. P. Phillips</b>Outdoor lap pool and a seasonal feature pool. 7000 Dr Phillips Blvd.</div>
    <div><b>Frank DeLuca</b>Pool, plus a water park that is closed for the season. Ocala.</div>
    <div><b>Golden Triangle</b>Outdoor pool. Tavares.</div>
    <div><b>J. Douglas Williams</b>Outdoor pool. Lake Mary.</div>
    <div><b>Lake Nona</b>Outdoor pool. 9055 Northlake Pkwy.</div>
    <div><b>Leonard &amp; Marjorie Williams</b>Outdoor pool and splash pad. Packing District.</div>
    <div><b>Osceola County</b>Outdoor pool and splash pad. Kissimmee.</div>
    <div><b>Oviedo</b>Indoor pool. 7900 Red Bug Lake Rd.</div>
    <div><b>Roper</b>Outdoor pool. Winter Garden.</div>
    <div><b>South Orlando</b>Outdoor pool. 814 W Oak Ridge Rd.</div>
    <div><b>Titusville</b>Outdoor pool. 2400 Harrison St.</div>
    <div><b>Wayne Densch</b>Outdoor pool. 870 N Hastings St.</div>
    <div><b>Winter Park</b>Lap pool and splash pool. 1201 N Lakemont Ave.</div>
  </div>
</section>

"""


PAGES = [
    ("index.html", "Swimming at the Y — YMCA of Central Florida (preview)",
     "Every YMCA of Central Florida pool on one live calendar.", HUB),
    ("lap-swim.html", "Lap Swim — YMCA of Central Florida (preview)",
     "Lap swim at all fourteen Ys, one day at a time.", LAP),
    ("swim-lessons.html", "Swim Lessons — YMCA of Central Florida (preview)",
     "Every fall group swim lesson session at every Y, by level.", LESSONS),
    ("swim-team.html", "Swim Teams — YMCA of Central Florida (preview)",
     "Developmental and USA Swimming practice times.", TEAM),
    ("water-fitness.html", "Water Fitness — YMCA of Central Florida (preview)",
     "Water fitness classes at every Y.", FIT),
    ("open-swim.html", "Open & Family Swim — YMCA of Central Florida (preview)",
     "Recreational swim, splash pads and feature pools.", OPEN),
    ("locations.html", "One Y, the whole week — YMCA of Central Florida (preview)",
     "Everything in one Y's pools for the week.", ONE),
]

if __name__ == "__main__":
    for slug, title, description, body in PAGES:
        with open(os.path.join(HERE, slug), "w", encoding="utf-8") as f:
            f.write(shell(slug, title, description, body))
        print("wrote", slug)
